export interface SeoMatrixPage {
  slug: string;
  bankName: string;
  targetFormat: string;
  targetLabel: string;
}

const FINANCIAL_INSTITUTIONS = Array.from(
  new Set([
    "JPMorgan Chase",
    "Bank of America",
    "Wells Fargo",
    "Citibank",
    "Capital One",
    "PNC Bank",
    "US Bank",
    "Truist",
    "Goldman Sachs",
    "Morgan Stanley",
    "Charles Schwab",
    "American Express",
    "Discover",
    "Ally Bank",
    "Synchrony Bank",
    "SoFi",
    "Robinhood",
    "Fidelity",
    "Navy Federal Credit Union",
    "Citizens Bank",
    "Fifth Third Bank",
    "KeyBank",
    "M&T Bank",
    "Regions Bank",
    "Huntington Bank",
    "BMO Harris",
    "TD Bank",
    "First Republic",
    "Comerica",
    "Santander Bank",
    "HSBC",
    "Barclays",
    "Lloyds Bank",
    "NatWest",
    "Royal Bank of Scotland",
    "Halifax",
    "Monzo",
    "Starling Bank",
    "Revolut",
    "Wise",
    "Metro Bank",
    "TSB Bank",
    "Virgin Money",
    "Nationwide Building Society",
    "Co-operative Bank",
    "Atom Bank",
    "Aldermore",
    "Yorkshire Building Society",
    "Skipton Building Society",
    "Bank of Scotland",
    "Deutsche Bank",
    "Commerzbank",
    "N26",
    "bunq",
    "ABN AMRO",
    "ING",
    "Rabobank",
    "SNS Bank",
    "Triodos Bank",
    "BNP Paribas",
    "Societe Generale",
    "Credit Agricole",
    "La Banque Postale",
    "Boursorama",
    "Hello bank!",
    "CIC",
    "LCL",
    "BPCE",
    "Crédit Mutuel",
    "Saxo Bank",
    "Danske Bank",
    "Nordea",
    "Swedbank",
    "SEB",
    "Handelsbanken",
    "DNB",
    "SpareBank 1",
    "Klarna",
    "Santander",
    "BBVA",
    "CaixaBank",
    "Banco Sabadell",
    "Bankinter",
    "Banco de Crédito Social Cooperativo",
    "Unicaja",
    "Kutxabank",
    "Banco BPM",
    "UniCredit",
    "Intesa Sanpaolo",
    "Monte dei Paschi di Siena",
    "FinecoBank",
    "BPER Banca",
    "Poste Italiane",
    "Mediobanca",
    "PKO Bank Polski",
    "mBank",
    "Bank Pekao",
    "Alior Bank",
    "ING Bank Slaski",
    "OTP Bank",
    "Erste Bank",
    "Raiffeisen Bank",
    "KBC Bank",
    "Belfius",
    "AIB",
    "Bank of Ireland",
    "Permanent TSB",
    "Alpha Bank",
    "Eurobank",
    "Piraeus Bank",
    "National Bank of Greece",
    "Ziraat Bankasi",
    "Isbank",
    "Garanti BBVA",
    "Akbank",
    "Yapi Kredi",
    "QNB Finansbank",
    "Tinkoff",
    "Sberbank",
    "VTB Bank",
    "Bank of China",
    "Industrial and Commercial Bank of China",
    "China Construction Bank",
    "Agricultural Bank of China",
    "China Merchants Bank",
    "Ping An Bank",
    "WeBank",
    "MYbank",
    "Standard Chartered",
    "DBS Bank",
    "OCBC Bank",
    "UOB",
    "Maybank",
    "CIMB",
    "Public Bank",
    "RHB Bank",
    "Hong Leong Bank",
    "Bank Islam",
    "Mandiri",
    "BCA",
    "BNI",
    "BRI",
    "PermataBank",
    "Bank Danamon",
    "UnionBank",
    "BDO Unibank",
    "Metrobank",
    "RCBC",
    "Security Bank",
    "Maya Bank",
    "GoTyme Bank",
    "GCash",
    "PayMaya",
    "Kasikornbank",
    "Bangkok Bank",
    "Siam Commercial Bank",
    "Krungthai Bank",
    "Krungsri",
    "TMBThanachart",
    "HDFC Bank",
    "ICICI Bank",
    "State Bank of India",
    "Axis Bank",
    "Kotak Mahindra Bank",
    "IDFC FIRST Bank",
    "Yes Bank",
    "IndusInd Bank",
    "Punjab National Bank",
    "Bank of Baroda",
    "Canara Bank",
    "Union Bank of India",
    "Paytm Payments Bank",
    "Airtel Payments Bank",
    "Nubank",
    "Banco do Brasil",
    "Itau Unibanco",
    "Bradesco",
    "Caixa Economica Federal",
    "Banco Inter",
    "PicPay",
    "Neon",
    "C6 Bank",
    "Santander Brasil",
    "BTG Pactual",
    "Banco Original",
    "Mercado Pago",
    "Banco Bice",
    "Banco de Chile",
    "Banco Estado",
    "Scotiabank Chile",
    "BCI",
    "Santander Chile",
    "Banco Falabella",
    "Banco de Credito del Peru",
    "Interbank",
    "BBVA Peru",
    "Scotiabank Peru",
    "Banco Pichincha",
    "Davivienda",
    "Bancolombia",
    "Banco de Bogota",
    "Banco Popular Colombia",
    "Nequi",
    "Lulo Bank",
    "Banco de Venezuela",
    "Banesco",
    "Banco Mercantil",
    "Banco Nacional de Mexico",
    "BBVA Mexico",
    "Banorte",
    "Santander Mexico",
    "HSBC Mexico",
    "Banco Azteca",
    "Inbursa",
    "BanCoppel",
    "Scotiabank Mexico",
    "Wise US",
    "Payoneer",
    "Stripe Treasury",
    "Brex",
    "Mercury",
    "Airwallex",
    "PayPal",
    "Skrill",
    "Neteller",
    "Remitly",
    "Western Union",
    "Standard Bank",
    "First National Bank South Africa",
    "Absa",
    "Nedbank",
    "Capitec",
    "TymeBank",
    "Investec",
    "Access Bank",
    "GTBank",
    "Zenith Bank",
    "First Bank of Nigeria",
    "UBA",
    "Fidelity Bank Nigeria",
    "Sterling Bank",
    "Wema Bank",
    "Moniepoint",
    "OPay",
    "Kuda",
    "PalmPay",
    "Ecobank",
    "Stanbic IBTC",
    "FCMB",
    "Keystone Bank",
    "Union Bank Nigeria",
    "CalBank",
    "GCB Bank",
    "Absa Ghana",
    "Equity Bank",
    "KCB Bank",
    "Co-operative Bank Kenya",
    "NCBA Bank",
    "Stanbic Bank Kenya",
    "I&M Bank",
    "Absa Kenya",
    "Bank of Kigali",
    "CRDB Bank",
    "NMB Bank Tanzania",
    "Equity Bank Rwanda",
    "QNB",
    "Emirates NBD",
    "Abu Dhabi Commercial Bank",
    "First Abu Dhabi Bank",
    "Mashreq",
    "Dubai Islamic Bank",
    "RAKBANK",
    "Al Rajhi Bank",
    "Riyad Bank",
    "Saudi National Bank",
    "Bank Albilad",
    "Bank AlJazira",
    "Kuwait Finance House",
    "Burgan Bank",
    "Bank Muscat",
    "Bank Dhofar",
    "Ahli Bank",
    "Doha Bank",
    "Qatar Islamic Bank",
    "Commercial Bank of Qatar",
    "BCA Syariah",
    "Bank Syariah Indonesia",
  ])
);

export const TARGET_FORMATS = [
  { id: "excel", label: "Excel" },
  { id: "csv", label: "CSV" },
  { id: "json", label: "JSON" },
  { id: "google-sheets", label: "Google Sheets" },
] as const;

function slugify(value: string) {
  return value
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/[\s_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export const seoPages: SeoMatrixPage[] = FINANCIAL_INSTITUTIONS.flatMap((bankName) =>
  TARGET_FORMATS.map((target) => ({
    slug: `${slugify(bankName)}-to-${target.id}`,
    bankName,
    targetFormat: target.id,
    targetLabel: target.label,
  }))
);

export const allPages = seoPages.map((page) => page.slug);
const SEO_PAGE_LOOKUP = new Map(seoPages.map((page) => [page.slug, page] as const));

export function findSeoPageBySlug(slug: string) {
  return SEO_PAGE_LOOKUP.get(slug);
}

export function getRelatedFormatSlug(page: SeoMatrixPage) {
  const nextFormat =
    page.targetFormat === "excel"
      ? "csv"
      : page.targetFormat === "csv"
        ? "excel"
        : page.targetFormat === "json"
          ? "google-sheets"
          : "json";

  return `${slugify(page.bankName)}-to-${nextFormat}`;
}
