export type ToolAccent = "red" | "blue" | "green" | "purple" | "orange";
export type ToolCategory =
  | "Organize"
  | "Optimize"
  | "Convert to PDF"
  | "Convert from PDF"
  | "Edit"
  | "Security"
  | "Intelligence"
  | "Developer Tools"
  | "Financial Tools";
export type ToolInputType = "number" | "text" | "select" | "password" | "textarea";
export type ToolMode = "file" | "form";
export type ToolProvider = "local" | "cloudconvert" | "gemini" | "hybrid";

export interface ToolInput {
  name: string;
  label: string;
  type: ToolInputType;
  placeholder?: string;
  options?: string[];
  helpText?: string;
  step?: string;
  min?: number;
  required?: boolean;
}

export interface ToolDefinition {
  id: string;
  title: string;
  category: ToolCategory;
  description: string;
  seoTitle?: string;
  seoDescription?: string;
  iconName: string;
  accent: ToolAccent;
  featured?: boolean;
  buttonLabel: string;
  mode: ToolMode;
  provider: ToolProvider;
  resultPreview?: "json-tree";
  fileAccept?: string;
  allowsMultipleFiles?: boolean;
  dropHint?: string;
  inputs: ToolInput[];
  keywords?: string[];
}

const CATEGORY_ORDER: ToolCategory[] = [
  "Organize",
  "Optimize",
  "Convert to PDF",
  "Convert from PDF",
  "Edit",
  "Security",
  "Intelligence",
  "Developer Tools",
  "Financial Tools",
];

function createFileTool(tool: Omit<ToolDefinition, "mode">): ToolDefinition {
  return {
    ...tool,
    mode: "file",
  };
}

function createFormTool(
  tool: Omit<ToolDefinition, "mode" | "fileAccept" | "allowsMultipleFiles" | "dropHint">
): ToolDefinition {
  return {
    ...tool,
    mode: "form",
  };
}

export const TOOLS: ToolDefinition[] = [
  createFileTool({
    id: "statement-to-csv",
    title: "Account Statement to CSV",
    category: "Intelligence",
    description: "Turn account statements into clean CSV rows.",
    iconName: "statement-to-csv",
    accent: "red",
    featured: true,
    buttonLabel: "Select Account Statement",
    provider: "hybrid",
    fileAccept: ".pdf",
    dropHint: "Drop your account statement here or pick a PDF from your device.",
    inputs: [
      {
        name: "statement_type",
        label: "Statement Type",
        type: "select",
        options: ["Checking", "Savings", "Credit Card"],
        helpText: "This helps us read dates and amounts more cleanly.",
      },
    ],
    keywords: ["csv", "account", "statement", "financial report", "transactions"],
  }),
  createFileTool({
    id: "merge-pdf",
    title: "Merge PDF",
    category: "Organize",
    description: "Join many PDFs into one file.",
    iconName: "merge-pdf",
    accent: "blue",
    featured: true,
    buttonLabel: "Select PDF Files",
    provider: "local",
    fileAccept: ".pdf",
    allowsMultipleFiles: true,
    dropHint: "Drop two or more PDF files here to combine them.",
    inputs: [],
    keywords: ["combine", "join", "pdf"],
  }),
  createFileTool({
    id: "split-pdf",
    title: "Split PDF",
    category: "Organize",
    description: "Break one PDF into smaller files.",
    iconName: "split-pdf",
    accent: "orange",
    buttonLabel: "Select PDF File",
    provider: "local",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here and we will split each page into its own file.",
    inputs: [
      {
        name: "page_ranges",
        label: "Page Ranges",
        type: "text",
        placeholder: "1-2,4",
        helpText: "Leave this blank to export every page as its own PDF.",
      },
    ],
    keywords: ["split", "pages", "pdf"],
  }),
  createFileTool({
    id: "organize-pdf",
    title: "Organize PDF",
    category: "Organize",
    description: "Put PDF pages in the order you want.",
    iconName: "organize-pdf",
    accent: "purple",
    buttonLabel: "Select PDF File",
    provider: "local",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here and choose the page order below.",
    inputs: [
      {
        name: "page_order",
        label: "Page Order",
        type: "text",
        placeholder: "1,3,2,4",
        helpText: "Use page numbers separated by commas.",
        required: true,
      },
    ],
    keywords: ["reorder", "organize", "pdf"],
  }),
  createFileTool({
    id: "remove-pages",
    title: "Remove Pages",
    category: "Organize",
    description: "Delete the pages you do not need.",
    iconName: "remove-pages",
    accent: "red",
    buttonLabel: "Select PDF File",
    provider: "local",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here and list the pages you want to remove.",
    inputs: [
      {
        name: "pages_to_remove",
        label: "Pages to Remove",
        type: "text",
        placeholder: "2,5-6",
        helpText: "Use commas and ranges like 2,5-6.",
        required: true,
      },
    ],
    keywords: ["delete", "remove", "pages"],
  }),
  createFileTool({
    id: "compress-pdf",
    title: "Compress PDF",
    category: "Optimize",
    description: "Make a PDF lighter so it is easier to share.",
    iconName: "compress-pdf",
    accent: "green",
    featured: true,
    buttonLabel: "Select PDF File",
    provider: "cloudconvert",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here to create a smaller copy.",
    inputs: [],
    keywords: ["compress", "smaller", "optimize"],
  }),
  createFileTool({
    id: "repair-pdf",
    title: "Repair PDF",
    category: "Optimize",
    description: "Clean a PDF and try to open it again.",
    iconName: "repair-pdf",
    accent: "orange",
    buttonLabel: "Select PDF File",
    provider: "cloudconvert",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here to rebuild the file structure.",
    inputs: [],
    keywords: ["repair", "fix", "pdf"],
  }),
  createFileTool({
    id: "word-to-pdf",
    title: "Word to PDF",
    category: "Convert to PDF",
    description: "Turn a Word file into a PDF.",
    iconName: "word-to-pdf",
    accent: "blue",
    buttonLabel: "Select Word File",
    provider: "cloudconvert",
    fileAccept: ".docx,.doc",
    dropHint: "Drop a Word file here to make a simple PDF copy.",
    inputs: [],
    keywords: ["docx", "word", "pdf"],
  }),
  createFileTool({
    id: "excel-to-pdf",
    title: "Excel to PDF",
    category: "Convert to PDF",
    description: "Turn a spreadsheet into a PDF.",
    iconName: "excel-to-pdf",
    accent: "green",
    buttonLabel: "Select Spreadsheet",
    provider: "cloudconvert",
    fileAccept: ".xlsx,.xls,.csv",
    dropHint: "Drop a spreadsheet here to make a clean PDF report.",
    inputs: [],
    keywords: ["excel", "spreadsheet", "xlsx", "csv"],
  }),
  createFileTool({
    id: "ppt-to-pdf",
    title: "PPT to PDF",
    category: "Convert to PDF",
    description: "Turn a slide deck into a PDF.",
    iconName: "ppt-to-pdf",
    accent: "orange",
    buttonLabel: "Select Presentation",
    provider: "cloudconvert",
    fileAccept: ".pptx",
    dropHint: "Drop a PowerPoint file here to make a PDF handout.",
    inputs: [],
    keywords: ["ppt", "pptx", "slides", "presentation"],
  }),
  createFileTool({
    id: "jpg-to-pdf",
    title: "JPG to PDF",
    category: "Convert to PDF",
    description: "Turn pictures into one PDF.",
    iconName: "jpg-to-pdf",
    accent: "purple",
    buttonLabel: "Select Images",
    provider: "cloudconvert",
    fileAccept: ".jpg,.jpeg,.png,.webp",
    allowsMultipleFiles: true,
    dropHint: "Drop one or more images here to turn them into a PDF.",
    inputs: [],
    keywords: ["jpg", "png", "images", "pdf"],
  }),
  createFileTool({
    id: "html-to-pdf",
    title: "HTML to PDF",
    category: "Convert to PDF",
    description: "Turn a web page file into a PDF.",
    iconName: "html-to-pdf",
    accent: "blue",
    buttonLabel: "Select HTML File",
    provider: "cloudconvert",
    fileAccept: ".html,.htm,.txt",
    dropHint: "Drop an HTML file here to make a readable PDF copy.",
    inputs: [],
    keywords: ["html", "web page", "pdf"],
  }),
  createFileTool({
    id: "pdf-to-word",
    title: "PDF to Word",
    category: "Convert from PDF",
    description: "Pull text out of a PDF into Word.",
    iconName: "pdf-to-word",
    accent: "blue",
    featured: true,
    buttonLabel: "Select PDF File",
    provider: "cloudconvert",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here to export the text into a Word file.",
    inputs: [],
    keywords: ["pdf", "word", "docx"],
  }),
  createFileTool({
    id: "pdf-to-excel",
    title: "PDF to Excel",
    category: "Convert from PDF",
    description: "Pull PDF rows into a spreadsheet.",
    iconName: "pdf-to-excel",
    accent: "green",
    featured: true,
    buttonLabel: "Select PDF File",
    provider: "cloudconvert",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here to export tables and lines into Excel.",
    inputs: [],
    keywords: ["pdf", "excel", "xlsx", "tables"],
  }),
  createFileTool({
    id: "pdf-to-ppt",
    title: "PDF to PPT",
    category: "Convert from PDF",
    description: "Turn PDF text into a slide deck.",
    iconName: "pdf-to-ppt",
    accent: "orange",
    featured: true,
    buttonLabel: "Select PDF File",
    provider: "cloudconvert",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here to make a simple presentation.",
    inputs: [],
    keywords: ["pdf", "ppt", "slides"],
  }),
  createFileTool({
    id: "pdf-to-jpg",
    title: "PDF to JPG",
    category: "Convert from PDF",
    description: "Turn PDF pages into picture files.",
    iconName: "pdf-to-jpg",
    accent: "purple",
    buttonLabel: "Select PDF File",
    provider: "cloudconvert",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here to export each page as an image.",
    inputs: [],
    keywords: ["pdf", "jpg", "image"],
  }),
  createFileTool({
    id: "pdf-to-pdfa",
    title: "PDF to PDF/A",
    category: "Convert from PDF",
    description: "Make a safer copy for long-term keeping.",
    iconName: "pdf-to-pdfa",
    accent: "red",
    buttonLabel: "Select PDF File",
    provider: "cloudconvert",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here to make an archival-style copy.",
    inputs: [],
    keywords: ["archive", "pdf/a", "pdfa"],
  }),
  createFileTool({
    id: "rotate-pdf",
    title: "Rotate PDF",
    category: "Edit",
    description: "Turn PDF pages the right way up.",
    iconName: "rotate-pdf",
    accent: "blue",
    buttonLabel: "Select PDF File",
    provider: "local",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here and pick how much to rotate it.",
    inputs: [
      {
        name: "rotation",
        label: "Rotation",
        type: "select",
        options: ["90", "180", "270"],
        required: true,
      },
    ],
    keywords: ["rotate", "turn", "pages"],
  }),
  createFileTool({
    id: "page-numbers",
    title: "Page Numbers",
    category: "Edit",
    description: "Add page numbers to every page.",
    iconName: "page-numbers",
    accent: "orange",
    buttonLabel: "Select PDF File",
    provider: "local",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here to stamp page numbers on it.",
    inputs: [
      {
        name: "start_number",
        label: "Start Number",
        type: "number",
        placeholder: "1",
        min: 1,
      },
    ],
    keywords: ["numbers", "pages", "footer"],
  }),
  createFileTool({
    id: "watermark-pdf",
    title: "Watermark PDF",
    category: "Edit",
    description: "Put light text over each page.",
    iconName: "watermark-pdf",
    accent: "purple",
    buttonLabel: "Select PDF File",
    provider: "local",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here and add the text you want to show on every page.",
    inputs: [
      {
        name: "watermark_text",
        label: "Watermark Text",
        type: "text",
        placeholder: "CONFIDENTIAL",
        required: true,
      },
    ],
    keywords: ["watermark", "stamp", "confidential"],
  }),
  createFileTool({
    id: "edit-pdf",
    title: "Edit PDF",
    category: "Edit",
    description: "Add a simple note to your PDF.",
    iconName: "edit-pdf",
    accent: "green",
    buttonLabel: "Select PDF File",
    provider: "local",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here and add a note to the first page.",
    inputs: [
      {
        name: "note_text",
        label: "Note Text",
        type: "textarea",
        placeholder: "Approved for review",
        required: true,
      },
    ],
    keywords: ["edit", "note", "annotate"],
  }),
  createFileTool({
    id: "compare-pdf",
    title: "Compare PDF",
    category: "Edit",
    description: "Compare two PDF versions and see what changed.",
    iconName: "compare-pdf",
    accent: "blue",
    buttonLabel: "Select Two PDFs",
    provider: "local",
    fileAccept: ".pdf",
    allowsMultipleFiles: true,
    dropHint: "Drop two PDF versions here and Logic Vault will build a clean change report.",
    inputs: [],
    keywords: ["compare pdf", "pdf diff", "version comparison", "secure PDF"],
  }),
  createFileTool({
    id: "redact-pdf",
    title: "Redact PDF",
    category: "Security",
    description: "Black out sensitive areas before sharing a PDF.",
    iconName: "redact-pdf",
    accent: "red",
    buttonLabel: "Select PDF File",
    provider: "local",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here and list the page areas you want permanently blacked out.",
    inputs: [
      {
        name: "redaction_zones",
        label: "Redaction Zones",
        type: "textarea",
        placeholder: "1:72,650,240,36\nall:48,48,180,24",
        required: true,
        helpText:
          "Use page:x,y,width,height in PDF points. Use all: for every page. Coordinates start at the bottom-left.",
      },
      {
        name: "redaction_label",
        label: "Redaction Label",
        type: "text",
        placeholder: "REDACTED",
        helpText: "Optional label printed inside each black-out box.",
      },
    ],
    keywords: ["redact pdf", "black out pdf", "sanitize pdf", "secure PDF"],
  }),
  createFileTool({
    id: "crop-pdf",
    title: "Crop PDF",
    category: "Edit",
    description: "Trim PDF margins and focus each page.",
    iconName: "crop-pdf",
    accent: "purple",
    buttonLabel: "Select PDF File",
    provider: "local",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here and enter top, right, bottom, and left margins.",
    inputs: [
      {
        name: "crop_margins",
        label: "Crop Margins",
        type: "text",
        placeholder: "36,36,36,36",
        required: true,
        helpText: "Enter top,right,bottom,left margins in PDF points.",
      },
    ],
    keywords: ["crop pdf", "trim pdf", "pdf margins", "secure PDF"],
  }),
  createFileTool({
    id: "scan-to-pdf",
    title: "Scan to PDF",
    category: "Convert to PDF",
    description: "Turn phone captures or scans into one clean PDF.",
    iconName: "scan-to-pdf",
    accent: "green",
    buttonLabel: "Select Scans",
    provider: "local",
    fileAccept: ".jpg,.jpeg,.png,.webp",
    allowsMultipleFiles: true,
    dropHint: "Drop phone photos or scan images here and Logic Vault will package them as a PDF.",
    inputs: [],
    keywords: ["scan to pdf", "mobile scan pdf", "image scan", "secure PDF"],
  }),
  createFileTool({
    id: "unlock-pdf",
    title: "Unlock PDF",
    category: "Security",
    description: "Open a Logic Vault locked PDF with your code.",
    iconName: "unlock-pdf",
    accent: "blue",
    buttonLabel: "Select Locked File",
    provider: "local",
    fileAccept: ".lvpdf",
    dropHint: "Drop one locked Logic Vault PDF here and enter the unlock code.",
    inputs: [
      {
        name: "password",
        label: "Unlock Code",
        type: "password",
        placeholder: "Enter your code",
        required: true,
      },
    ],
    keywords: ["unlock", "secure", "password"],
  }),
  createFileTool({
    id: "protect-pdf",
    title: "Protect PDF",
    category: "Security",
    description: "Lock a PDF with a secret code.",
    iconName: "protect-pdf",
    accent: "red",
    buttonLabel: "Select PDF File",
    provider: "local",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here and add a code to lock it.",
    inputs: [
      {
        name: "password",
        label: "Lock Code",
        type: "password",
        placeholder: "Create a code",
        required: true,
      },
    ],
    keywords: ["protect", "secure", "password"],
  }),
  createFileTool({
    id: "sign-pdf",
    title: "Sign PDF",
    category: "Security",
    description: "Stamp your name onto a PDF.",
    iconName: "sign-pdf",
    accent: "green",
    buttonLabel: "Select PDF File",
    provider: "local",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here and type the name you want to sign with.",
    inputs: [
      {
        name: "signer_name",
        label: "Signer Name",
        type: "text",
        placeholder: "Jamie Rivera",
        required: true,
      },
      {
        name: "sign_reason",
        label: "Reason",
        type: "text",
        placeholder: "Approved",
      },
    ],
    keywords: ["sign", "signature", "approval"],
  }),
  createFileTool({
    id: "ai-summarizer",
    title: "AI Summarizer",
    category: "Intelligence",
    description: "Get the main points from a PDF fast.",
    iconName: "ai-summarizer",
    accent: "purple",
    featured: true,
    buttonLabel: "Select PDF File",
    provider: "gemini",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here to get a short text summary.",
    inputs: [
      {
        name: "summary_length",
        label: "Summary Length",
        type: "select",
        options: ["Short", "Medium", "Long"],
      },
    ],
    keywords: ["summary", "ai", "overview"],
  }),
  createFileTool({
    id: "translate-pdf",
    title: "Translate PDF",
    category: "Intelligence",
    description: "Get a plain-text version in another language.",
    iconName: "translate-pdf",
    accent: "blue",
    buttonLabel: "Select PDF File",
    provider: "gemini",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here and choose the language you want.",
    inputs: [
      {
        name: "target_language",
        label: "Target Language",
        type: "select",
        options: ["Spanish", "French", "German", "Portuguese"],
        required: true,
      },
    ],
    keywords: ["translate", "language", "text"],
  }),
  createFileTool({
    id: "ocr-pdf",
    title: "OCR PDF",
    category: "Intelligence",
    description: "Pull readable text out of a PDF.",
    iconName: "ocr-pdf",
    accent: "orange",
    featured: true,
    buttonLabel: "Select PDF File",
    provider: "hybrid",
    fileAccept: ".pdf",
    dropHint: "Drop one PDF here to extract the text inside it.",
    inputs: [],
    keywords: ["ocr", "scan", "extract text"],
  }),
  createFileTool({
    id: "ai-expense-categorizer",
    title: "AI Expense Categorizer",
    category: "Intelligence",
    description: "Group spending lines into simple expense buckets.",
    iconName: "ai-expense-categorizer",
    accent: "green",
    buttonLabel: "Select Report File",
    provider: "gemini",
    fileAccept: ".csv,.xlsx,.pdf",
    dropHint: "Drop a CSV, spreadsheet, or PDF report here to label your expenses.",
    inputs: [
      {
        name: "report_style",
        label: "Report Style",
        type: "select",
        options: ["Simple", "Detailed"],
      },
    ],
    keywords: ["expenses", "categories", "spending", "ai"],
  }),
  createFileTool({
    id: "financial-health-score",
    title: "Financial Health Score",
    category: "Intelligence",
    description: "Get a quick score for cash flow and spending habits.",
    iconName: "financial-health-score",
    accent: "blue",
    buttonLabel: "Select Financial Report",
    provider: "gemini",
    fileAccept: ".csv,.xlsx,.pdf",
    dropHint: "Drop a report here to see your overall financial health score.",
    inputs: [
      {
        name: "risk_view",
        label: "Risk View",
        type: "select",
        options: ["Balanced", "Conservative", "Aggressive"],
      },
    ],
    keywords: ["score", "cash flow", "health", "finance"],
  }),
  createFileTool({
    id: "json-universal-converter",
    title: "JSON Universal Converter",
    category: "Developer Tools",
    description: "Turn XML, CSV, or YAML into clean JSON.",
    seoTitle: "Fastest Online JSON Universal Converter - Logic Vault - High-Performance Utility.",
    seoDescription:
      "Use our JSON Universal Converter to turn XML, CSV, or YAML into JSON locally. Fast, private, and 100% free for developer workflows.",
    iconName: "json-universal-converter",
    accent: "blue",
    featured: true,
    buttonLabel: "Select Source File",
    provider: "local",
    fileAccept: ".xml,.csv,.yaml,.yml",
    dropHint: "Drop an XML, CSV, or YAML file here and convert it into structured JSON.",
    inputs: [
      {
        name: "source_format",
        label: "Source Format",
        type: "select",
        options: ["Auto", "XML", "CSV", "YAML"],
        helpText: "Auto-detect is best for most files.",
      },
      {
        name: "root_key",
        label: "Wrap in Root Key",
        type: "text",
        placeholder: "records",
        helpText: "Optional. Add one top-level key around the output JSON.",
      },
    ],
    keywords: ["json converter", "xml to json", "csv to json", "yaml to json", "developer tool"],
  }),
  createFormTool({
    id: "json-formatter-validator",
    title: "JSON Formatter & Validator",
    category: "Developer Tools",
    description: "Clean messy JSON and catch syntax errors fast.",
    seoTitle:
      "Fastest Online JSON Formatter & Validator - Logic Vault - High-Performance Utility.",
    seoDescription:
      "Use our JSON Formatter & Validator to clean JSON, detect syntax issues, and verify payloads locally without uploads.",
    iconName: "json-formatter-validator",
    accent: "green",
    buttonLabel: "Format JSON",
    provider: "local",
    inputs: [
      {
        name: "json_input",
        label: "JSON Input",
        type: "textarea",
        placeholder: '{\n  "status": "ok"\n}',
        required: true,
        helpText: "Paste raw JSON and Logic Vault will prettify it or point to the error.",
      },
    ],
    keywords: ["json formatter", "json validator", "prettify json", "syntax checker"],
  }),
  createFormTool({
    id: "json-to-typescript-interface",
    title: "JSON to TypeScript Interface",
    category: "Developer Tools",
    description: "Generate TypeScript interfaces from JSON objects.",
    seoTitle:
      "Fastest Online JSON to TypeScript Interface - Logic Vault - High-Performance Utility.",
    seoDescription:
      "Use our JSON to TypeScript Interface tool to generate typed interfaces from JSON locally. Fast, private, and built for dev teams.",
    iconName: "json-to-typescript-interface",
    accent: "purple",
    buttonLabel: "Generate Interface",
    provider: "local",
    inputs: [
      {
        name: "json_input",
        label: "JSON Input",
        type: "textarea",
        placeholder: '{\n  "user": {\n    "id": 1,\n    "email": "hello@example.com"\n  }\n}',
        required: true,
        helpText: "Paste a sample JSON object so Logic Vault can infer the interface shape.",
      },
      {
        name: "interface_name",
        label: "Root Interface Name",
        type: "text",
        placeholder: "ApiResponse",
      },
    ],
    keywords: ["json to typescript", "typescript interface generator", "json schema", "developer"],
  }),
  createFormTool({
    id: "json-minifier",
    title: "JSON Minifier",
    category: "Developer Tools",
    description: "Compress JSON so it is ready for production use.",
    seoTitle: "Fastest Online JSON Minifier - Logic Vault - High-Performance Utility.",
    seoDescription:
      "Use our JSON Minifier to compress payloads locally and prepare clean production-ready JSON without sending your data anywhere.",
    iconName: "json-minifier",
    accent: "red",
    buttonLabel: "Minify JSON",
    provider: "local",
    inputs: [
      {
        name: "json_input",
        label: "JSON Input",
        type: "textarea",
        placeholder: '{\n  "items": [1, 2, 3]\n}',
        required: true,
      },
    ],
    keywords: ["json minifier", "compress json", "compact json", "developer utility"],
  }),
  createFormTool({
    id: "json-tree-viewer",
    title: "JSON Tree Viewer",
    category: "Developer Tools",
    description: "Explore nested JSON in a clean expandable tree.",
    seoTitle: "Fastest Online JSON Tree Viewer - Logic Vault - High-Performance Utility.",
    seoDescription:
      "Use our JSON Tree Viewer to inspect nested payloads visually, expand objects, and trace structure locally with no uploads.",
    iconName: "json-tree-viewer",
    accent: "blue",
    buttonLabel: "Build Tree",
    provider: "local",
    resultPreview: "json-tree",
    inputs: [
      {
        name: "json_input",
        label: "JSON Input",
        type: "textarea",
        placeholder: '{\n  "account": {\n    "transactions": []\n  }\n}',
        required: true,
      },
    ],
    keywords: ["json tree", "json viewer", "expand json", "developer explorer"],
  }),
  createFormTool({
    id: "base64-encoder",
    title: "Base64 Encoder",
    category: "Developer Tools",
    description: "Reserve a clean Base64 route while the live encoder ships next.",
    seoTitle: "Fastest Online Base64 Encoder - Logic Vault - High-Performance Utility.",
    seoDescription:
      "Use our Base64 Encoder route to prepare for quick text encoding workflows. The hardened encoder is queued for the next developer release.",
    iconName: "base64-encoder",
    accent: "orange",
    buttonLabel: "Reserve Tool",
    provider: "local",
    inputs: [
      {
        name: "plain_text",
        label: "Plain Text",
        type: "textarea",
        placeholder: "Paste the text you plan to encode.",
        required: true,
      },
    ],
    keywords: ["base64 encoder", "base64 utility", "developer placeholder"],
  }),
  createFormTool({
    id: "jwt-debugger",
    title: "JWT Debugger",
    category: "Developer Tools",
    description: "Reserve a secure token inspector route for future debugging.",
    seoTitle: "Fastest Online JWT Debugger - Logic Vault - High-Performance Utility.",
    seoDescription:
      "Use our JWT Debugger route to reserve a secure token inspection workflow. The hardened signed-claims viewer is queued next.",
    iconName: "jwt-debugger",
    accent: "green",
    buttonLabel: "Reserve Tool",
    provider: "local",
    inputs: [
      {
        name: "jwt_token",
        label: "JWT Token",
        type: "textarea",
        placeholder: "Paste a token to reserve this debugging workflow.",
        required: true,
      },
    ],
    keywords: ["jwt debugger", "token inspector", "developer placeholder"],
  }),
  createFormTool({
    id: "yield-calculator",
    title: "Yield Calculator",
    category: "Financial Tools",
    description: "See how much profit your property or asset makes.",
    iconName: "yield-calculator",
    accent: "blue",
    buttonLabel: "Enter Data",
    provider: "local",
    inputs: [
      {
        name: "purchase_price",
        label: "Purchase Price",
        type: "number",
        placeholder: "250000",
        required: true,
        min: 0,
      },
      {
        name: "monthly_rent",
        label: "Monthly Rent",
        type: "number",
        placeholder: "2200",
        required: true,
        min: 0,
      },
      {
        name: "annual_costs",
        label: "Annual Costs",
        type: "number",
        placeholder: "3600",
        required: true,
        min: 0,
      },
    ],
    keywords: ["yield", "property", "rent", "cap rate"],
  }),
  createFormTool({
    id: "roi-tracker",
    title: "ROI Tracker",
    category: "Financial Tools",
    description: "Check if your marketing is making money.",
    iconName: "roi-tracker",
    accent: "green",
    buttonLabel: "Enter Data",
    provider: "local",
    inputs: [
      {
        name: "marketing_spend",
        label: "Marketing Spend",
        type: "number",
        placeholder: "5000",
        required: true,
        min: 0,
      },
      {
        name: "marketing_revenue",
        label: "Revenue From Campaign",
        type: "number",
        placeholder: "14000",
        required: true,
        min: 0,
      },
    ],
    keywords: ["roi", "marketing", "revenue", "profit"],
  }),
  createFormTool({
    id: "landed-cost-calculator",
    title: "Landed Cost Calculator",
    category: "Financial Tools",
    description: "See the true cost of bringing a product in.",
    iconName: "landed-cost-calculator",
    accent: "orange",
    buttonLabel: "Enter Data",
    provider: "local",
    inputs: [
      {
        name: "unit_cost",
        label: "Unit Cost",
        type: "number",
        placeholder: "18",
        required: true,
        min: 0,
      },
      {
        name: "shipping_cost",
        label: "Shipping",
        type: "number",
        placeholder: "4",
        required: true,
        min: 0,
      },
      {
        name: "duty_rate",
        label: "Duty Rate (%)",
        type: "number",
        placeholder: "8",
        required: true,
        min: 0,
      },
    ],
    keywords: ["landed cost", "shipping", "duty", "imports"],
  }),
  createFormTool({
    id: "marketing-budget-tool",
    title: "Marketing Budget Tool",
    category: "Financial Tools",
    description: "Plan how much to spend to hit your goal.",
    iconName: "marketing-budget-tool",
    accent: "purple",
    buttonLabel: "Enter Data",
    provider: "local",
    inputs: [
      {
        name: "revenue_target",
        label: "Revenue Target",
        type: "number",
        placeholder: "100000",
        required: true,
        min: 0,
      },
      {
        name: "budget_percent",
        label: "Budget Percent (%)",
        type: "number",
        placeholder: "12",
        required: true,
        min: 0,
      },
      {
        name: "target_cpa",
        label: "Target CPA",
        type: "number",
        placeholder: "40",
        required: true,
        min: 0,
      },
    ],
    keywords: ["marketing budget", "planning", "ads", "cpa"],
  }),
  createFormTool({
    id: "tax-estimator",
    title: "Tax Estimator",
    category: "Financial Tools",
    description: "Quickly guess your tax obligations.",
    iconName: "tax-estimator",
    accent: "red",
    buttonLabel: "Enter Data",
    provider: "local",
    inputs: [
      {
        name: "taxable_income",
        label: "Taxable Income",
        type: "number",
        placeholder: "80000",
        required: true,
        min: 0,
      },
      {
        name: "deductible_expenses",
        label: "Deductible Expenses",
        type: "number",
        placeholder: "12000",
        required: true,
        min: 0,
      },
      {
        name: "estimated_tax_rate",
        label: "Estimated Tax Rate (%)",
        type: "number",
        placeholder: "22",
        required: true,
        min: 0,
      },
    ],
    keywords: ["tax", "estimate", "liability"],
  }),
  createFormTool({
    id: "business-valuation-tool",
    title: "Business Valuation Tool",
    category: "Financial Tools",
    description: "Estimate what a business may be worth.",
    iconName: "business-valuation-tool",
    accent: "green",
    buttonLabel: "Enter Data",
    provider: "local",
    inputs: [
      {
        name: "annual_ebitda",
        label: "Annual EBITDA",
        type: "number",
        placeholder: "150000",
        required: true,
        min: 0,
      },
      {
        name: "valuation_multiple",
        label: "Valuation Multiple",
        type: "number",
        placeholder: "4.5",
        required: true,
        min: 0,
        step: "0.1",
      },
    ],
    keywords: ["valuation", "business", "ebitda", "multiple"],
  }),
];

export function findToolBySlug(slug: string) {
  return TOOLS.find((tool) => tool.id === slug);
}

export function groupTools(tools: ToolDefinition[]) {
  return CATEGORY_ORDER.map((category) => ({
    category,
    tools: tools.filter((tool) => tool.category === category),
  })).filter((group) => group.tools.length > 0);
}
