create table if not exists public.contact_submission_logs (
  id bigint generated by default as identity primary key,
  ip_hashed text not null,
  status text not null check (status in ('accepted', 'stealth', 'rate-limited')),
  purpose text,
  city text,
  created_at timestamptz not null default now()
);

create index if not exists contact_submission_logs_ip_hashed_created_at_idx
  on public.contact_submission_logs (ip_hashed, created_at desc);
